services:
  # Serviço para o Dev Container (VS Code)
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jupyter_devcontainer
    env_file:
      - .env
    volumes:
      - .:/workspace
      - pip_cache:/root/.cache/pip
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    command: sleep infinity

  # Serviço para o Jupyter no browser
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jupyter_lab
    ports:
      - "8888:8888"
    env_file:
      - .env
    volumes:
      - .:/workspace
      - pip_cache:/root/.cache/pip
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    command: >
      jupyter lab
      --ip=0.0.0.0
      --port=8888
      --no-browser
      --allow-root
      --ServerApp.token=''
      --ServerApp.password=''
      --notebook-dir=/workspace

volumes:
  pip_cache: